My Portfolio Second version
Agape-nduwamungu/my_portfolio pull request #5
Opened 2023-03-25 20:58 UTC by Agape-nduwamungu

Ensured:
- that the added part for index and styles files is visible.
- that the linters are working correctly.

2023-03-25 20:59 UTC, Agape-nduwamungu commented
Had some conflicts.

2023-03-25 22:00 UTC, zieeco requested changes
Hi @Agape-nduwamungu ,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️
- Good commit message :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 22:00 UTC, zieeco commented on index.html
> +                    <img src="images/placeholder.svg" alt="placeholder1" class="project-2-img" />
- Hey, the images you've added here do not exits in your image folder. please, kindly check to add them as they are broken right now.

2023-03-25 22:00 UTC, zieeco commented on index.html
> +                    <img src="images/placeholder.svg" alt="placeholder1" class="project-3-img" />
- Hey, the images you've added here do not exits in your image folder. please, kindly check to add them as they are broken right now.

2023-03-25 22:00 UTC, zieeco commented on index.html
> +                    <img src="images/placeholder.svg" alt="placeholder1" class="project-4-img" />
- Hey, the images you've added here do not exits in your image folder. please, kindly check to add them as they are broken right now.

2023-03-25 22:00 UTC, zieeco commented on index.html
> +                    <img src="images/placeholder.svg" alt="placeholder1" class="project-5-img" />
- Hey, the images you've added here do not exits in your image folder. please, kindly check to add them as they are broken right now.

2023-03-25 22:00 UTC, zieeco commented on index.html
> +                    <img src="images/placeholder.svg" alt="placeholder1" class="project-6-img" />
- Hey, the images you've added here do not exits in your image folder. please, kindly check to add them as they are broken right now.

2023-03-25 22:00 UTC, zieeco commented on index.html
> +                        <button class="project-card-btn button popup" type="button">See Project</button>
### ALL LIST ITEMS AND BUTTONS IN THE WORKS SECTION
- 
- Hey, please, let's style the list of items and align the buttons correctly to match the design as much as we can to improve our design. kindly check the images below:

*your design*
![Screenshot from 2023-03-25 22-52-57](https://user-images.githubusercontent.com/59397159/227744103-33b69221-c8f1-457f-a2fe-a394ff164faa.png)

*Figma design*
![Screenshot from 2023-03-25 22-52-35](https://user-images.githubusercontent.com/59397159/227744107-14851994-81ef-46c4-b9e2-9662580ea4f9.png)

2023-03-25 22:00 UTC, zieeco commented on index.html
> +        </section>
- Hey, kindly improve your about section. it's missing all the tags on the cards and the images are not showing including the background image. please, let's work on this to improve our design. chek the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1-468&t=zM3zI9tBvX4156tQ-0) to improve your design.

2023-03-28 12:54 UTC, closed without merging

2023-03-28 12:54 UTC, Agape-nduwamungu commented
Opened a new pull request